const knowledge = `
sorts
   %% Restarants table
    #id = 1..5. %%1..271
    #position =  1..4. %%1..182.
    #restaurantName = {rdsciprv,
qqpxcvcp,
ouyceuyb,
gbxjblpd
}.
    #score = 0..50.
    #rating = 0..97.
    #category = {ipsgxfrn,
mbqdomyp,
ttkxvvno,
eimkemgr,
ktxeefhg,
gdmfeoks,
intqqmnk,
rahdrcot,
bqctdiau,
xlvjogtb,
yduqrbnh,
duhwkrid,
fzjugfbl,
hozdveen,
dfmnogqq,
iidscufg,
yavgbbkr,
ldiryiri,
yliyhxlx,
nrkaudde,
ryvbsweh,
intqqmnk,
eimkemgr}.

    #priceRange = 1..3.
    #fullAddress = {elkgnltp,
autpqcog,
dauxlkec,
wtneuvan}.
    #zipcode = {bbvltflp,
euqzmpyx,
vlbhkipn,
vlbhkipn}.

    #foodCategory = {ydgrcaxx,
nzdgtqbo,
tjsbfdlb,
vmynpqdj,
moklfdsc,
onpahegy,
xlvjogtb,
onsjxlnr,
iidscufg,
flzufqiu,
dlmarohb,
xkzcvext,
cbilfzcy,
evfghufy,
jbtiseet,
xrsjfzgy,
ywnieaen,
gchgefrv,
eybdoxlx,
eslnvjue,
foukgbls,
iuwygtzn,
yduqrbnh,
afnlienn,
nhmhjcaq,
xlvjogtb,
znkweirv,
xkzcvext,
jbjzajbo,
wmhqovtu,
yeydvadl,
syljbbhn,
xqlvvvmb,
rzkzzptq,
xkzcvext,
ekwueian}.
    #foodDescription = {gsdphudq,
cesecozs,
jonhulzc,
mtsyqhtp,
ianaigqi,
mjabhnfo,
hbeaatqn,
zohgqgiu,
kkfvrjnw,
brploune,
etcmuvas,
hnucbyhg,
xnfuyyte,
kmjapnlx,
kfheqdxn,
pcfyogmu,
sgmbclmn,
ikgztaay,
oemaacbt,
iyamngba,
lizccvci,
kfheqdxn,
yiljppcv,
gmmihqox,
jtdeowet,
ujwugrxv,
ypcwquzu,
gxavewdw,
dvbyczqd,
smdxrakp,
hblceqsf,
kidmsfcb,
nndkylno,
rrqnawga,
prrmctjh,
bhjkuydl,
nfilefol,
yugzyffc,
fnhzxcbk,
llmlbcnv,
ahljrpko,
dajigcpp,
rlpzdjzj,
mmvoagey,
mwtkuvsk,
nmnooqzu,
xnqrpuoc,
xgxowvyo,
zfmlhhfz,
rvluolpa,
djpvorjj,
hhbqakxj,
fqevunbk,
iwtonoyh,
qomunaum,
bndmcjcq,
emfggvml,
dkweibef,
kfheqdxn,
wwrumjhp,
ecuodzjv,
kqkpnuwf,
dohjdqqy,
esslaygp,
kfheqdxn,
mblcspzq,
rsgtnzxy}.

    #foodItem = {agtujvnh,
gaqvsphs,
mhswceig,
jrpmtiuo,
hhcbpnyk,
vekkhnna,
kertodfh,
ojdbwrnl,
xicpfzmk,
mbpdljnt,
pnyzrver,
xalffohh,
shsfkewg,
ovvocceu,
bcqylwcn,
sufngthl,
tdkgynyx,
gscrcxle,
ctqwqotl,
fhkjcuix,
xrjvodfv,
ndsbtrnu,
bhldydul,
soacgjye,
ndtuyfxd,
hhdwvuya,
mqdvtmsr,
udpirazf,
ewnamoly,
kgygdgyz,
mfqfjpyc,
jsfdibyu,
jrijpolr,
qoekvqrm,
grqzxvnx,
qxsqylcr,
lfdhance,
zogvxojf,
bwtkvyvg,
zyderedh,
ckryfdat,
rtyttxtq,
fezengow,
xycbqwqs,
ggohelni,
pghoarts,
hdxvyfkw,
bdnxvwdt,
sneilvbm,
vekujcyb,
vbqvpudj,
detlyzpn,
pixhfgwy,
tucdtesn,
zjivagfc,
pocdgqpx,
julxgomt,
rdnwkxse,
uhrleups,
teshunzg,
dpvjjobh,
vnzcbgoj,
fpfvwopw,
nimlmhqj,
syaeyiqt,
bgbpevgj,
skpuidoc,
wzzxbqbi,
eiywblcq,
npqincrv,
hughxwlz,
ejxoeepm,
rifdtdti,
swxadfgj,
uzwfrjpb,
mzhujdjk,
szxladpz,
ydmtzkvi,
omdaviio,
gqkfjjqp,
jmgqkrcc,
gdtteork,
qysqwclu,
nnayldat,
egxmrjoq,
xwijkzsh,
qpxaphka,
oujiwsvg,
peafczyl,
gecokluf,
dmnidguz,
klrnhmbp,
ljplrkoo,
dqitlkrq,
sqdiepsj,
uejttnhe,
ejvssbwo,
jcsmtvdy,
onadfnqq,
tlkfzane,
kpjqiitr,
nxhiyvvj,
nfoucwhf,
gmukkfzm,
gkdoenjp,
cxrjzjmu,
qabbqlhh,
engwmpan,
cqwihloe,
cduxrhkx,
aewfsyjk,
jzhvnjbv,
vdtjgejf,
hnrbehjn,
lzcyiycz,
jbqdfvrn,
ribbwtoq,
bcaaqxbw,
zaamhdky,
lwktbvjq,
tmcojnai,
avrsesbh,
jnuylowp,
ceunovse,
ajbksafr,
zpemfycz,
tzfqvihp,
nboepgqc,
nvdiccpx,
seolwlcy,
mcpwbwig,
rusyftca,
hpqvqpou,
fshmajsj,
bgptcqit,
byqzsjaj,
pfwpinrc,
cjqmyglb,
rfustlek,
dtgwcjqv,
ozbubsnf,
nwqlrizb,
xbwsusbf,
dkfeufbh,
smvcmohg,
hpuxyyjh,
vluxpnrd,
irlrtnzb,
fimkhlxt,
piakseab,
xuoqvgim,
xofyxgmc,
kqolrgkx,
fovmpjqt,
mnwgmogq,
cflzxmun,
qdmrhuqc,
mnlrsdmy,
zrympsyv,
sfrwtzvw,
hnextklx,
ekmbbmug,
wyscfyzg,
ytdoszfx,
fyokvcda,
gdaasvgg,
ntxheika,
nyjlyoul,
mqfexupf,
ngklfnwi,
rnewugrg,
qujymaaz,
elcajzut,
cdcwgahh,
kyguzjwg,
kcilomsn,
katbjhhv,
jxjuyyiy,
ktqfblxt,
nsufqczt,
qpjraqwn,
gbngnwth,
ibcgmdas,
kxbdtpfs,
fatcigwp}.
    #foodPrice = 0..100.
predicates

    name(#id, #restaurantName).
    position(#id,#position).
    score(#id, #score).
    hasScore(#id).
    getScore(#id,#score).
    ratings(#id, #rating).
    hasRating(#id).
    getRating(#id, #rating).
    category(#id, #category).
    priceRange(#id, #priceRange).
    hasPriceRange(#id).
    getPriceRange(#id, #priceRange).
    fullAddress(#id, #fullAddress).
    zipcode(#id, #zipcode).
    
    positionByName(#restaurantName,#position).
    scoreByName(#restaurantName, #score).
    ratingsByName(#restaurantName, #rating).
    categoryByName(#restaurantName, #category).
    priceRangeByName(#restaurantName, #priceRange).
    fullAddressByName(#restaurantName, #fullAddress).
    zipcodeByName(#restaurantName, #zipcode).
    
    hasFoodCategory(#id,#foodCategory).
    categoryHasItem(#foodCategory,#foodItem).
    hasItem(#id,#foodItem).
    price(#foodItem,#foodPrice).
    description(#foodItem,#foodDescription).
    
    getRestaurantDetails(#id,#restaurantName,#position,#score,#rating,#priceRange,#fullAddress,#zipcode).
    getMenuByRestaurant(#id,#foodCategory,#foodItem, #foodPrice).
    
rules

    getRestaurantDetails(I,N,P,S,R,B,A,Z) :- name(I,N),
                                             position(I,P),
                                             score(I,S),
                                             ratings(I,R),
                                             priceRange(I,B),
                                             fullAddress(I,A),
                                             zipcode(I,Z).
                                             
                                             
    getMenuByRestaurant(I,C,F,P) :-   hasFoodCategory(I,C),
                                      categoryHasItem(C,F),
                                      price(F,P).

    %positionByName(X,Y) :- name(I,X), position(I,Y).
    %scoreByName(X,Y) :- name(I,X), score(I,Y).
    %ratingsByName(X,Y) :- name(I,X), ratings(I,Y).
    %categoryByName(X,Y) :- name(I,X), category(I,Y).
    %priceRangeByName(X,Y) :- name(I,X), priceRange(I,Y).
    %fullAddressByName(X,Y) :- name(I,X), fullAddress(I,Y).
    %zipcodeByName(X,Y) :- name(I,X), zipcode(I,Y).
    
    
    %-positionByName(X,Y) :- not positionByName(X,Y).
    %-scoreByName(X,Y) :- not scoreByName(X,Y).
    %-ratingsByName(X,Y) :- not ratingsByName(X,Y).
    %-categoryByName(X,Y) :- not categoryByName(X,Y).
    %-priceRangeByName(X,Y) :- not priceRangeByName(X,Y).
    %-fullAddressByName(X,Y) :- not fullAddressByName(X,Y).
    %-zipcodeByName(X,Y) :- not zipcodeByName(X,Y).
    
    %-name(X,Y) :- not name(X,Y).
    %-position(X,Y) :- not position(X,Y).
    %-score(X,Y) :- not score(X,Y).
    %-ratings(X,Y) :- not ratings(X,Y).
    %-category(X,Y) :- not category(X,Y).
    %-fullAddress(X,Y) :- not fullAddress(X,Y).
    %-zipcode(X,Y) :- not zipcode(X,Y).
    
    % default for priceRange
    hasPriceRange(X) :- priceRange(X,Y).
    getPriceRange(X,Y) :- priceRange(X,Y).
    getPriceRange(X,2) :- not hasPriceRange(X).
    % CWA - Price Range
    -getPriceRange(X,Y) :- not getPriceRange(X,Y).
    
    % default for rating
    hasRating(X) :- ratings(X,Y).
    getRating(X,Y) :- ratings(X,Y).
    getRating(X,0) :- not hasRating(X).
    
    % default for score
    hasScore(X) :- score(X,Y).
    getScore(X,Y) :- score(X,Y).
    getScore(X,25) :- not hasScore(X).

    
name(1,rdsciprv).
name(2,qqpxcvcp).
name(4,ouyceuyb).
name(5,gbxjblpd).

position(1,2).
position(2,1).
position(4,3).
position(5,4).
    
score(1,42).
score(2,49).
score(4,42).
score(5,31).

ratings(1,2).
ratings(2,69).
ratings(4,45).
ratings(5,34).
    
category(1,ipsgxfrn).
category(1,mbqdomyp).
category(1,ttkxvvno).
category(1,eimkemgr).
category(1,ktxeefhg).
category(1,gdmfeoks).
category(1,intqqmnk).
category(1,rahdrcot).
category(2,bqctdiau).
category(2,xlvjogtb).
category(2,yduqrbnh).
category(2,duhwkrid).
category(4,fzjugfbl).
category(4,hozdveen).
category(4,dfmnogqq).
category(4,iidscufg).
category(4,yavgbbkr).
category(4,ldiryiri).
category(4,yliyhxlx).
category(4,nrkaudde).
category(5,ryvbsweh).
category(5,intqqmnk).
category(5,eimkemgr).
    
priceRange(1,1).

priceRange(4,3).
priceRange(5,2).

fullAddress(1,elkgnltp).
fullAddress(2,autpqcog).
fullAddress(4,dauxlkec).
fullAddress(5,wtneuvan).

zipcode(1,bbvltflp).
zipcode(2,euqzmpyx).
zipcode(4,vlbhkipn).
zipcode(5,vlbhkipn).

hasFoodCategory(1,ydgrcaxx).
hasFoodCategory(1,ydgrcaxx).
hasFoodCategory(1,ydgrcaxx).
hasFoodCategory(1,nzdgtqbo).
hasFoodCategory(1,nzdgtqbo).
hasFoodCategory(1,nzdgtqbo).
hasFoodCategory(1,nzdgtqbo).
hasFoodCategory(1,tjsbfdlb).
hasFoodCategory(1,tjsbfdlb).
hasFoodCategory(1,vmynpqdj).
hasFoodCategory(1,moklfdsc).
hasFoodCategory(1,moklfdsc).
hasFoodCategory(1,onpahegy).
hasFoodCategory(1,onpahegy).
hasFoodCategory(1,xlvjogtb).
hasFoodCategory(1,onsjxlnr).
hasFoodCategory(1,onsjxlnr).
hasFoodCategory(1,onsjxlnr).
hasFoodCategory(1,onsjxlnr).
hasFoodCategory(1,iidscufg).
hasFoodCategory(1,iidscufg).
hasFoodCategory(1,iidscufg).
hasFoodCategory(1,flzufqiu).
hasFoodCategory(1,dlmarohb).
hasFoodCategory(2,xkzcvext).
hasFoodCategory(2,xkzcvext).
hasFoodCategory(2,xkzcvext).
hasFoodCategory(2,xkzcvext).
hasFoodCategory(2,xkzcvext).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,cbilfzcy).
hasFoodCategory(2,evfghufy).
hasFoodCategory(2,evfghufy).
hasFoodCategory(2,evfghufy).
hasFoodCategory(2,jbtiseet).
hasFoodCategory(2,jbtiseet).
hasFoodCategory(2,jbtiseet).
hasFoodCategory(2,jbtiseet).
hasFoodCategory(2,xrsjfzgy).
hasFoodCategory(2,xrsjfzgy).
hasFoodCategory(2,xrsjfzgy).
hasFoodCategory(2,xrsjfzgy).
hasFoodCategory(2,xrsjfzgy).
hasFoodCategory(2,xrsjfzgy).
hasFoodCategory(2,xrsjfzgy).
hasFoodCategory(2,xrsjfzgy).
hasFoodCategory(2,ywnieaen).
hasFoodCategory(2,ywnieaen).
hasFoodCategory(2,ywnieaen).
hasFoodCategory(2,ywnieaen).
hasFoodCategory(2,gchgefrv).
hasFoodCategory(2,gchgefrv).
hasFoodCategory(2,gchgefrv).
hasFoodCategory(2,gchgefrv).
hasFoodCategory(2,gchgefrv).
hasFoodCategory(2,gchgefrv).
hasFoodCategory(2,gchgefrv).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eybdoxlx).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,eslnvjue).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,foukgbls).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,iuwygtzn).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(2,yduqrbnh).
hasFoodCategory(4,xkzcvext).
hasFoodCategory(4,xkzcvext).
hasFoodCategory(4,xkzcvext).
hasFoodCategory(4,xkzcvext).
hasFoodCategory(4,xkzcvext).
hasFoodCategory(4,jbjzajbo).
hasFoodCategory(4,jbjzajbo).
hasFoodCategory(4,jbjzajbo).
hasFoodCategory(4,jbjzajbo).
hasFoodCategory(4,jbjzajbo).
hasFoodCategory(4,jbjzajbo).
hasFoodCategory(4,wmhqovtu).
hasFoodCategory(4,wmhqovtu).
hasFoodCategory(4,wmhqovtu).
hasFoodCategory(4,wmhqovtu).
hasFoodCategory(4,wmhqovtu).
hasFoodCategory(4,wmhqovtu).
hasFoodCategory(4,wmhqovtu).
hasFoodCategory(4,yeydvadl).
hasFoodCategory(4,yeydvadl).
hasFoodCategory(4,yeydvadl).
hasFoodCategory(4,yeydvadl).
hasFoodCategory(4,yeydvadl).
hasFoodCategory(4,syljbbhn).
hasFoodCategory(4,syljbbhn).
hasFoodCategory(4,syljbbhn).
hasFoodCategory(4,syljbbhn).
hasFoodCategory(4,syljbbhn).
hasFoodCategory(4,xqlvvvmb).
hasFoodCategory(4,xqlvvvmb).
hasFoodCategory(4,xqlvvvmb).
hasFoodCategory(4,xqlvvvmb).
hasFoodCategory(4,xqlvvvmb).
hasFoodCategory(4,xqlvvvmb).
hasFoodCategory(4,rzkzzptq).
hasFoodCategory(4,rzkzzptq).
hasFoodCategory(4,rzkzzptq).
hasFoodCategory(4,rzkzzptq).
hasFoodCategory(4,rzkzzptq).
hasFoodCategory(4,rzkzzptq).
hasFoodCategory(5,xkzcvext).
hasFoodCategory(5,xkzcvext).
hasFoodCategory(5,ekwueian).
hasFoodCategory(5,ekwueian).

categoryHasItem(ydgrcaxx,agtujvnh).
categoryHasItem(ydgrcaxx,gaqvsphs).
categoryHasItem(ydgrcaxx,mhswceig).
categoryHasItem(nzdgtqbo,jrpmtiuo).
categoryHasItem(nzdgtqbo,hhcbpnyk).
categoryHasItem(nzdgtqbo,vekkhnna).
categoryHasItem(nzdgtqbo,kertodfh).
categoryHasItem(tjsbfdlb,ojdbwrnl).
categoryHasItem(tjsbfdlb,xicpfzmk).
categoryHasItem(vmynpqdj,mbpdljnt).
categoryHasItem(moklfdsc,pnyzrver).
categoryHasItem(moklfdsc,xalffohh).
categoryHasItem(onpahegy,shsfkewg).
categoryHasItem(onpahegy,ovvocceu).
categoryHasItem(xlvjogtb,bcqylwcn).
categoryHasItem(onsjxlnr,sufngthl).
categoryHasItem(onsjxlnr,tdkgynyx).
categoryHasItem(onsjxlnr,gscrcxle).
categoryHasItem(onsjxlnr,ctqwqotl).
categoryHasItem(iidscufg,fhkjcuix).
categoryHasItem(iidscufg,xrjvodfv).
categoryHasItem(iidscufg,ndsbtrnu).
categoryHasItem(flzufqiu,bhldydul).
categoryHasItem(dlmarohb,soacgjye).
categoryHasItem(xkzcvext,ndtuyfxd).
categoryHasItem(xkzcvext,hhdwvuya).
categoryHasItem(xkzcvext,mqdvtmsr).
categoryHasItem(xkzcvext,udpirazf).
categoryHasItem(xkzcvext,ewnamoly).
categoryHasItem(cbilfzcy,kgygdgyz).
categoryHasItem(cbilfzcy,mfqfjpyc).
categoryHasItem(cbilfzcy,ndtuyfxd).
categoryHasItem(cbilfzcy,jsfdibyu).
categoryHasItem(cbilfzcy,jrijpolr).
categoryHasItem(cbilfzcy,ewnamoly).
categoryHasItem(cbilfzcy,qoekvqrm).
categoryHasItem(cbilfzcy,grqzxvnx).
categoryHasItem(cbilfzcy,qxsqylcr).
categoryHasItem(cbilfzcy,lfdhance).
categoryHasItem(cbilfzcy,zogvxojf).
categoryHasItem(cbilfzcy,bwtkvyvg).
categoryHasItem(evfghufy,zyderedh).
categoryHasItem(evfghufy,ckryfdat).
categoryHasItem(evfghufy,rtyttxtq).
categoryHasItem(jbtiseet,fezengow).
categoryHasItem(jbtiseet,xycbqwqs).
categoryHasItem(jbtiseet,ggohelni).
categoryHasItem(jbtiseet,pghoarts).
categoryHasItem(xrsjfzgy,hdxvyfkw).
categoryHasItem(xrsjfzgy,bdnxvwdt).
categoryHasItem(xrsjfzgy,sneilvbm).
categoryHasItem(xrsjfzgy,vekujcyb).
categoryHasItem(xrsjfzgy,vbqvpudj).
categoryHasItem(xrsjfzgy,detlyzpn).
categoryHasItem(xrsjfzgy,pixhfgwy).
categoryHasItem(xrsjfzgy,tucdtesn).
categoryHasItem(ywnieaen,zjivagfc).
categoryHasItem(ywnieaen,pocdgqpx).
categoryHasItem(ywnieaen,julxgomt).
categoryHasItem(ywnieaen,rdnwkxse).
categoryHasItem(gchgefrv,uhrleups).
categoryHasItem(gchgefrv,teshunzg).
categoryHasItem(gchgefrv,dpvjjobh).
categoryHasItem(gchgefrv,mqdvtmsr).
categoryHasItem(gchgefrv,vnzcbgoj).
categoryHasItem(gchgefrv,fpfvwopw).
categoryHasItem(gchgefrv,nimlmhqj).
categoryHasItem(eybdoxlx,syaeyiqt).
categoryHasItem(eybdoxlx,bgbpevgj).
categoryHasItem(eybdoxlx,skpuidoc).
categoryHasItem(eybdoxlx,wzzxbqbi).
categoryHasItem(eybdoxlx,eiywblcq).
categoryHasItem(eybdoxlx,npqincrv).
categoryHasItem(eybdoxlx,hughxwlz).
categoryHasItem(eybdoxlx,ejxoeepm).
categoryHasItem(eybdoxlx,rifdtdti).
categoryHasItem(eybdoxlx,swxadfgj).
categoryHasItem(eybdoxlx,uzwfrjpb).
categoryHasItem(eslnvjue,mzhujdjk).
categoryHasItem(eslnvjue,szxladpz).
categoryHasItem(eslnvjue,ydmtzkvi).
categoryHasItem(eslnvjue,omdaviio).
categoryHasItem(eslnvjue,gqkfjjqp).
categoryHasItem(eslnvjue,jmgqkrcc).
categoryHasItem(eslnvjue,gdtteork).
categoryHasItem(eslnvjue,qysqwclu).
categoryHasItem(eslnvjue,nnayldat).
categoryHasItem(eslnvjue,egxmrjoq).
categoryHasItem(eslnvjue,xwijkzsh).
categoryHasItem(eslnvjue,qpxaphka).
categoryHasItem(eslnvjue,oujiwsvg).
categoryHasItem(foukgbls,peafczyl).
categoryHasItem(foukgbls,gecokluf).
categoryHasItem(foukgbls,dmnidguz).
categoryHasItem(foukgbls,klrnhmbp).
categoryHasItem(foukgbls,ljplrkoo).
categoryHasItem(foukgbls,dqitlkrq).
categoryHasItem(foukgbls,sqdiepsj).
categoryHasItem(foukgbls,uejttnhe).
categoryHasItem(foukgbls,ejvssbwo).
categoryHasItem(foukgbls,jcsmtvdy).
categoryHasItem(foukgbls,onadfnqq).
categoryHasItem(foukgbls,tlkfzane).
categoryHasItem(foukgbls,kpjqiitr).
categoryHasItem(foukgbls,nxhiyvvj).
categoryHasItem(foukgbls,nfoucwhf).
categoryHasItem(foukgbls,gmukkfzm).
categoryHasItem(iuwygtzn,gkdoenjp).
categoryHasItem(iuwygtzn,cxrjzjmu).
categoryHasItem(iuwygtzn,qabbqlhh).
categoryHasItem(iuwygtzn,engwmpan).
categoryHasItem(iuwygtzn,cqwihloe).
categoryHasItem(iuwygtzn,cduxrhkx).
categoryHasItem(iuwygtzn,aewfsyjk).
categoryHasItem(iuwygtzn,jzhvnjbv).
categoryHasItem(iuwygtzn,hhdwvuya).
categoryHasItem(iuwygtzn,vdtjgejf).
categoryHasItem(iuwygtzn,hnrbehjn).
categoryHasItem(iuwygtzn,lzcyiycz).
categoryHasItem(iuwygtzn,jbqdfvrn).
categoryHasItem(iuwygtzn,ribbwtoq).
categoryHasItem(iuwygtzn,bcaaqxbw).
categoryHasItem(yduqrbnh,zaamhdky).
categoryHasItem(yduqrbnh,lwktbvjq).
categoryHasItem(yduqrbnh,tmcojnai).
categoryHasItem(yduqrbnh,avrsesbh).
categoryHasItem(yduqrbnh,jnuylowp).
categoryHasItem(yduqrbnh,ceunovse).
categoryHasItem(yduqrbnh,ajbksafr).
categoryHasItem(yduqrbnh,zpemfycz).
categoryHasItem(yduqrbnh,tzfqvihp).
categoryHasItem(yduqrbnh,nboepgqc).
categoryHasItem(yduqrbnh,nvdiccpx).
categoryHasItem(yduqrbnh,udpirazf).
categoryHasItem(yduqrbnh,seolwlcy).
categoryHasItem(yduqrbnh,mcpwbwig).
categoryHasItem(yduqrbnh,rusyftca).
categoryHasItem(yduqrbnh,hpqvqpou).
categoryHasItem(yduqrbnh,fshmajsj).
categoryHasItem(yduqrbnh,bgptcqit).
categoryHasItem(yduqrbnh,byqzsjaj).
categoryHasItem(afnlienn,pfwpinrc).
categoryHasItem(afnlienn,cjqmyglb).
categoryHasItem(nhmhjcaq,rfustlek).
categoryHasItem(xlvjogtb,dtgwcjqv).
categoryHasItem(xlvjogtb,ozbubsnf).
categoryHasItem(znkweirv,nwqlrizb).
categoryHasItem(znkweirv,xbwsusbf).
categoryHasItem(znkweirv,dkfeufbh).
categoryHasItem(znkweirv,smvcmohg).
categoryHasItem(znkweirv,hpuxyyjh).
categoryHasItem(znkweirv,vluxpnrd).
categoryHasItem(xkzcvext,irlrtnzb).
categoryHasItem(xkzcvext,fimkhlxt).
categoryHasItem(xkzcvext,piakseab).
categoryHasItem(xkzcvext,xuoqvgim).
categoryHasItem(xkzcvext,xofyxgmc).
categoryHasItem(jbjzajbo,kqolrgkx).
categoryHasItem(jbjzajbo,fovmpjqt).
categoryHasItem(jbjzajbo,mnwgmogq).
categoryHasItem(jbjzajbo,cflzxmun).
categoryHasItem(jbjzajbo,qdmrhuqc).
categoryHasItem(jbjzajbo,mnlrsdmy).
categoryHasItem(wmhqovtu,zrympsyv).
categoryHasItem(wmhqovtu,sfrwtzvw).
categoryHasItem(wmhqovtu,hnextklx).
categoryHasItem(wmhqovtu,ekmbbmug).
categoryHasItem(wmhqovtu,wyscfyzg).
categoryHasItem(wmhqovtu,ytdoszfx).
categoryHasItem(wmhqovtu,fyokvcda).
categoryHasItem(yeydvadl,xofyxgmc).
categoryHasItem(yeydvadl,gdaasvgg).
categoryHasItem(yeydvadl,ntxheika).
categoryHasItem(yeydvadl,nyjlyoul).
categoryHasItem(yeydvadl,mqfexupf).
categoryHasItem(syljbbhn,ngklfnwi).
categoryHasItem(syljbbhn,rnewugrg).
categoryHasItem(syljbbhn,qujymaaz).
categoryHasItem(syljbbhn,elcajzut).
categoryHasItem(syljbbhn,cdcwgahh).
categoryHasItem(xqlvvvmb,kyguzjwg).
categoryHasItem(xqlvvvmb,irlrtnzb).
categoryHasItem(xqlvvvmb,kcilomsn).
categoryHasItem(xqlvvvmb,fimkhlxt).
categoryHasItem(xqlvvvmb,katbjhhv).
categoryHasItem(xqlvvvmb,jxjuyyiy).
categoryHasItem(rzkzzptq,ktqfblxt).
categoryHasItem(rzkzzptq,xuoqvgim).
categoryHasItem(rzkzzptq,nsufqczt).
categoryHasItem(rzkzzptq,qpjraqwn).
categoryHasItem(rzkzzptq,gbngnwth).
categoryHasItem(rzkzzptq,piakseab).
categoryHasItem(xkzcvext,ibcgmdas).
categoryHasItem(ekwueian,kxbdtpfs).
categoryHasItem(ekwueian,fatcigwp).

hasItem(1,agtujvnh).
hasItem(1,gaqvsphs).
hasItem(1,mhswceig).
hasItem(1,jrpmtiuo).
hasItem(1,hhcbpnyk).
hasItem(1,vekkhnna).
hasItem(1,kertodfh).
hasItem(1,ojdbwrnl).
hasItem(1,xicpfzmk).
hasItem(1,mbpdljnt).
hasItem(1,pnyzrver).
hasItem(1,xalffohh).
hasItem(1,shsfkewg).
hasItem(1,ovvocceu).
hasItem(1,bcqylwcn).
hasItem(1,sufngthl).
hasItem(1,tdkgynyx).
hasItem(1,gscrcxle).
hasItem(1,ctqwqotl).
hasItem(1,fhkjcuix).
hasItem(1,xrjvodfv).
hasItem(1,ndsbtrnu).
hasItem(1,bhldydul).
hasItem(1,soacgjye).
hasItem(2,ndtuyfxd).
hasItem(2,hhdwvuya).
hasItem(2,mqdvtmsr).
hasItem(2,udpirazf).
hasItem(2,ewnamoly).
hasItem(2,kgygdgyz).
hasItem(2,mfqfjpyc).
hasItem(2,ndtuyfxd).
hasItem(2,jsfdibyu).
hasItem(2,jrijpolr).
hasItem(2,ewnamoly).
hasItem(2,qoekvqrm).
hasItem(2,grqzxvnx).
hasItem(2,qxsqylcr).
hasItem(2,lfdhance).
hasItem(2,zogvxojf).
hasItem(2,bwtkvyvg).
hasItem(2,zyderedh).
hasItem(2,ckryfdat).
hasItem(2,rtyttxtq).
hasItem(2,fezengow).
hasItem(2,xycbqwqs).
hasItem(2,ggohelni).
hasItem(2,pghoarts).
hasItem(2,hdxvyfkw).
hasItem(2,bdnxvwdt).
hasItem(2,sneilvbm).
hasItem(2,vekujcyb).
hasItem(2,vbqvpudj).
hasItem(2,detlyzpn).
hasItem(2,pixhfgwy).
hasItem(2,tucdtesn).
hasItem(2,zjivagfc).
hasItem(2,pocdgqpx).
hasItem(2,julxgomt).
hasItem(2,rdnwkxse).
hasItem(2,uhrleups).
hasItem(2,teshunzg).
hasItem(2,dpvjjobh).
hasItem(2,mqdvtmsr).
hasItem(2,vnzcbgoj).
hasItem(2,fpfvwopw).
hasItem(2,nimlmhqj).
hasItem(2,syaeyiqt).
hasItem(2,bgbpevgj).
hasItem(2,skpuidoc).
hasItem(2,wzzxbqbi).
hasItem(2,eiywblcq).
hasItem(2,npqincrv).
hasItem(2,hughxwlz).
hasItem(2,ejxoeepm).
hasItem(2,rifdtdti).
hasItem(2,swxadfgj).
hasItem(2,uzwfrjpb).
hasItem(2,mzhujdjk).
hasItem(2,szxladpz).
hasItem(2,ydmtzkvi).
hasItem(2,omdaviio).
hasItem(2,gqkfjjqp).
hasItem(2,jmgqkrcc).
hasItem(2,gdtteork).
hasItem(2,qysqwclu).
hasItem(2,nnayldat).
hasItem(2,egxmrjoq).
hasItem(2,xwijkzsh).
hasItem(2,qpxaphka).
hasItem(2,oujiwsvg).
hasItem(2,peafczyl).
hasItem(2,gecokluf).
hasItem(2,dmnidguz).
hasItem(2,klrnhmbp).
hasItem(2,ljplrkoo).
hasItem(2,dqitlkrq).
hasItem(2,sqdiepsj).
hasItem(2,uejttnhe).
hasItem(2,ejvssbwo).
hasItem(2,jcsmtvdy).
hasItem(2,onadfnqq).
hasItem(2,tlkfzane).
hasItem(2,kpjqiitr).
hasItem(2,nxhiyvvj).
hasItem(2,nfoucwhf).
hasItem(2,gmukkfzm).
hasItem(2,gkdoenjp).
hasItem(2,cxrjzjmu).
hasItem(2,qabbqlhh).
hasItem(2,engwmpan).
hasItem(2,cqwihloe).
hasItem(2,cduxrhkx).
hasItem(2,aewfsyjk).
hasItem(2,jzhvnjbv).
hasItem(2,hhdwvuya).
hasItem(2,vdtjgejf).
hasItem(2,hnrbehjn).
hasItem(2,lzcyiycz).
hasItem(2,jbqdfvrn).
hasItem(2,ribbwtoq).
hasItem(2,bcaaqxbw).
hasItem(2,zaamhdky).
hasItem(2,lwktbvjq).
hasItem(2,tmcojnai).
hasItem(2,avrsesbh).
hasItem(2,jnuylowp).
hasItem(2,ceunovse).
hasItem(2,ajbksafr).
hasItem(2,zpemfycz).
hasItem(2,tzfqvihp).
hasItem(2,nboepgqc).
hasItem(2,nvdiccpx).
hasItem(2,udpirazf).
hasItem(2,seolwlcy).
hasItem(2,mcpwbwig).
hasItem(2,rusyftca).
hasItem(2,hpqvqpou).
hasItem(2,fshmajsj).
hasItem(2,bgptcqit).
hasItem(2,byqzsjaj).
hasItem(3,pfwpinrc).
hasItem(3,cjqmyglb).
hasItem(3,rfustlek).
hasItem(3,dtgwcjqv).
hasItem(3,ozbubsnf).
hasItem(3,nwqlrizb).
hasItem(3,xbwsusbf).
hasItem(3,dkfeufbh).
hasItem(3,smvcmohg).
hasItem(3,hpuxyyjh).
hasItem(3,vluxpnrd).
hasItem(4,irlrtnzb).
hasItem(4,fimkhlxt).
hasItem(4,piakseab).
hasItem(4,xuoqvgim).
hasItem(4,xofyxgmc).
hasItem(4,kqolrgkx).
hasItem(4,fovmpjqt).
hasItem(4,mnwgmogq).
hasItem(4,cflzxmun).
hasItem(4,qdmrhuqc).
hasItem(4,mnlrsdmy).
hasItem(4,zrympsyv).
hasItem(4,sfrwtzvw).
hasItem(4,hnextklx).
hasItem(4,ekmbbmug).
hasItem(4,wyscfyzg).
hasItem(4,ytdoszfx).
hasItem(4,fyokvcda).
hasItem(4,xofyxgmc).
hasItem(4,gdaasvgg).
hasItem(4,ntxheika).
hasItem(4,nyjlyoul).
hasItem(4,mqfexupf).
hasItem(4,ngklfnwi).
hasItem(4,rnewugrg).
hasItem(4,qujymaaz).
hasItem(4,elcajzut).
hasItem(4,cdcwgahh).
hasItem(4,kyguzjwg).
hasItem(4,irlrtnzb).
hasItem(4,kcilomsn).
hasItem(4,fimkhlxt).
hasItem(4,katbjhhv).
hasItem(4,jxjuyyiy).
hasItem(4,ktqfblxt).
hasItem(4,xuoqvgim).
hasItem(4,nsufqczt).
hasItem(4,qpjraqwn).
hasItem(4,gbngnwth).
hasItem(4,piakseab).
hasItem(5,ibcgmdas).
hasItem(5,kxbdtpfs).
hasItem(5,fatcigwp).


price(agtujvnh,17).
price(gaqvsphs,21).
price(mhswceig,11).
price(jrpmtiuo,9).
price(hhcbpnyk,7).
price(vekkhnna,11).
price(kertodfh,4).
price(ojdbwrnl,9).
price(xicpfzmk,8).
price(mbpdljnt,7).
price(pnyzrver,70).
price(xalffohh,100).
price(shsfkewg,21).
price(ovvocceu,17).
price(bcqylwcn,2).
price(sufngthl,3).
price(tdkgynyx,7).
price(gscrcxle,10).
price(ctqwqotl,2).
price(fhkjcuix,3).
price(xrjvodfv,7).
price(ndsbtrnu,10).
price(bhldydul,4).
price(soacgjye,4).
price(ndtuyfxd,18).
price(hhdwvuya,18).
price(mqdvtmsr,28).
price(udpirazf,17).
price(ewnamoly,23).
price(kgygdgyz,18).
price(mfqfjpyc,18).
price(ndtuyfxd,18).
price(jsfdibyu,23).
price(jrijpolr,13).
price(ewnamoly,23).
price(qoekvqrm,23).
price(grqzxvnx,23).
price(qxsqylcr,23).
price(lfdhance,23).
price(zogvxojf,24).
price(bwtkvyvg,4).
price(zyderedh,17).
price(ckryfdat,58).
price(rtyttxtq,17).
price(fezengow,40).
price(xycbqwqs,37).
price(ggohelni,17).
price(pghoarts,13).
price(hdxvyfkw,3).
price(bdnxvwdt,3).
price(sneilvbm,3).
price(vekujcyb,13).
price(vbqvpudj,9).
price(detlyzpn,9).
price(pixhfgwy,9).
price(tucdtesn,3).
price(zjivagfc,5).
price(pocdgqpx,5).
price(julxgomt,2).
price(rdnwkxse,36).
price(uhrleups,40).
price(teshunzg,35).
price(dpvjjobh,40).
price(mqdvtmsr,28).
price(vnzcbgoj,10).
price(fpfvwopw,19).
price(nimlmhqj,19).
price(syaeyiqt,22).
price(bgbpevgj,33).
price(skpuidoc,22).
price(wzzxbqbi,36).
price(eiywblcq,24).
price(npqincrv,24).
price(hughxwlz,23).
price(ejxoeepm,24).
price(rifdtdti,24).
price(swxadfgj,35).
price(uzwfrjpb,40).
price(mzhujdjk,24).
price(szxladpz,24).
price(ydmtzkvi,71).
price(omdaviio,40).
price(gqkfjjqp,35).
price(jmgqkrcc,14).
price(gdtteork,14).
price(qysqwclu,17).
price(nnayldat,19).
price(egxmrjoq,19).
price(xwijkzsh,33).
price(qpxaphka,40).
price(oujiwsvg,41).
price(peafczyl,30).
price(gecokluf,44).
price(dmnidguz,18).
price(klrnhmbp,22).
price(ljplrkoo,16).
price(dqitlkrq,8).
price(sqdiepsj,30).
price(uejttnhe,24).
price(ejvssbwo,25).
price(jcsmtvdy,43).
price(onadfnqq,25).
price(tlkfzane,22).
price(kpjqiitr,17).
price(nxhiyvvj,25).
price(nfoucwhf,25).
price(gmukkfzm,22).
price(gkdoenjp,37).
price(cxrjzjmu,37).
price(qabbqlhh,20).
price(engwmpan,32).
price(cqwihloe,35).
price(cduxrhkx,22).
price(aewfsyjk,53).
price(jzhvnjbv,41).
price(hhdwvuya,18).
price(vdtjgejf,30).
price(hnrbehjn,35).
price(lzcyiycz,47).
price(jbqdfvrn,40).
price(ribbwtoq,26).
price(bcaaqxbw,48).
price(zaamhdky,17).
price(lwktbvjq,17).
price(tmcojnai,31).
price(avrsesbh,18).
price(jnuylowp,18).
price(ceunovse,14).
price(ajbksafr,14).
price(zpemfycz,14).
price(tzfqvihp,11).
price(nboepgqc,13).
price(nvdiccpx,10).
price(udpirazf,17).
price(seolwlcy,16).
price(mcpwbwig,16).
price(rusyftca,10).
price(hpqvqpou,5).
price(fshmajsj,5).
price(bgptcqit,5).
price(byqzsjaj,17).
price(pfwpinrc,14).
price(cjqmyglb,17).

price(dtgwcjqv,2).
price(ozbubsnf,2).
price(nwqlrizb,10).
price(xbwsusbf,10).
price(dkfeufbh,10).
price(smvcmohg,12).
price(hpuxyyjh,10).
price(vluxpnrd,5).
price(irlrtnzb,4).
price(fimkhlxt,4).
price(piakseab,5).
price(xuoqvgim,5).
price(xofyxgmc,5).
price(kqolrgkx,4).
price(fovmpjqt,4).
price(mnwgmogq,4).
price(cflzxmun,4).
price(qdmrhuqc,4).
price(mnlrsdmy,4).
price(zrympsyv,2).
price(sfrwtzvw,2).
price(hnextklx,2).
price(ekmbbmug,2).
price(wyscfyzg,2).
price(ytdoszfx,2).
price(fyokvcda,2).
price(xofyxgmc,5).
price(gdaasvgg,5).
price(ntxheika,5).
price(nyjlyoul,6).
price(mqfexupf,3).
price(ngklfnwi,4).
price(rnewugrg,4).
price(qujymaaz,4).
price(elcajzut,4).
price(cdcwgahh,4).
price(kyguzjwg,4).
price(irlrtnzb,4).
price(kcilomsn,4).
price(fimkhlxt,4).
price(katbjhhv,4).
price(jxjuyyiy,4).
price(ktqfblxt,5).
price(xuoqvgim,5).
price(nsufqczt,5).
price(qpjraqwn,5).
price(gbngnwth,5).
price(piakseab,5).
price(ibcgmdas,8).
price(kxbdtpfs,7).
price(fatcigwp,0).

description(agtujvnh,gsdphudq).
description(gaqvsphs,cesecozs).
description(mhswceig,jonhulzc).
description(jrpmtiuo,mtsyqhtp).
description(hhcbpnyk,ianaigqi).
description(vekkhnna,mjabhnfo).
description(kertodfh,hbeaatqn).
description(ojdbwrnl,zohgqgiu).
description(xicpfzmk,kkfvrjnw).
description(mbpdljnt,brploune).
description(pnyzrver,etcmuvas).
description(xalffohh,hnucbyhg).
description(shsfkewg,xnfuyyte).
description(ovvocceu,kmjapnlx).
description(bcqylwcn,kfheqdxn).
description(sufngthl,pcfyogmu).
description(tdkgynyx,pcfyogmu).
description(gscrcxle,pcfyogmu).
description(ctqwqotl,sgmbclmn).
description(fhkjcuix,ikgztaay).
description(xrjvodfv,oemaacbt).
description(ndsbtrnu,ikgztaay).
description(bhldydul,iyamngba).
description(soacgjye,kfheqdxn).
description(ndtuyfxd,lizccvci).
description(hhdwvuya,kfheqdxn).
description(mqdvtmsr,yiljppcv).
description(udpirazf,gmmihqox).
description(ewnamoly,kfheqdxn).
description(kgygdgyz,jtdeowet).
description(mfqfjpyc,jtdeowet).
description(ndtuyfxd,lizccvci).
description(jsfdibyu,kfheqdxn).
description(jrijpolr,kfheqdxn).
description(ewnamoly,kfheqdxn).
description(qoekvqrm,ujwugrxv).
description(grqzxvnx,kfheqdxn).
description(qxsqylcr,kfheqdxn).
description(lfdhance,kfheqdxn).
description(zogvxojf,kfheqdxn).
description(bwtkvyvg,ypcwquzu).
description(zyderedh,gxavewdw).
description(ckryfdat,kfheqdxn).
description(rtyttxtq,kfheqdxn).
description(fezengow,kfheqdxn).
description(xycbqwqs,kfheqdxn).
description(ggohelni,kfheqdxn).
description(pghoarts,dvbyczqd).
description(hdxvyfkw,kfheqdxn).
description(bdnxvwdt,kfheqdxn).
description(sneilvbm,kfheqdxn).
description(vekujcyb,kfheqdxn).
description(vbqvpudj,kfheqdxn).
description(detlyzpn,kfheqdxn).
description(pixhfgwy,kfheqdxn).
description(tucdtesn,smdxrakp).
description(zjivagfc,kfheqdxn).
description(pocdgqpx,kfheqdxn).
description(julxgomt,hblceqsf).
description(rdnwkxse,kidmsfcb).
description(uhrleups,kfheqdxn).
description(teshunzg,kfheqdxn).
description(dpvjjobh,kfheqdxn).
description(mqdvtmsr,yiljppcv).
description(vnzcbgoj,kfheqdxn).
description(fpfvwopw,kfheqdxn).
description(nimlmhqj,nndkylno).
description(syaeyiqt,kfheqdxn).
description(bgbpevgj,kfheqdxn).
description(skpuidoc,kfheqdxn).
description(wzzxbqbi,kfheqdxn).
description(eiywblcq,kfheqdxn).
description(npqincrv,kfheqdxn).
description(hughxwlz,kfheqdxn).
description(ejxoeepm,rrqnawga).
description(rifdtdti,rrqnawga).
description(swxadfgj,rrqnawga).
description(uzwfrjpb,prrmctjh).
description(mzhujdjk,kfheqdxn).
description(szxladpz,kfheqdxn).
description(ydmtzkvi,kfheqdxn).
description(omdaviio,kfheqdxn).
description(gqkfjjqp,kfheqdxn).
description(jmgqkrcc,bhjkuydl).
description(gdtteork,nfilefol).
description(qysqwclu,yugzyffc).
description(nnayldat,fnhzxcbk).
description(egxmrjoq,llmlbcnv).
description(xwijkzsh,ahljrpko).
description(qpxaphka,dajigcpp).
description(oujiwsvg,dajigcpp).
description(peafczyl,kfheqdxn).
description(gecokluf,kfheqdxn).
description(dmnidguz,rlpzdjzj).
description(klrnhmbp,kfheqdxn).
description(ljplrkoo,kfheqdxn).
description(dqitlkrq,kfheqdxn).
description(sqdiepsj,kfheqdxn).
description(uejttnhe,kfheqdxn).
description(ejvssbwo,kfheqdxn).
description(jcsmtvdy,kfheqdxn).
description(onadfnqq,kfheqdxn).
description(tlkfzane,kfheqdxn).
description(kpjqiitr,kfheqdxn).
description(nxhiyvvj,kfheqdxn).
description(nfoucwhf,mmvoagey).
description(gmukkfzm,mwtkuvsk).
description(gkdoenjp,kfheqdxn).
description(cxrjzjmu,kfheqdxn).
description(qabbqlhh,kfheqdxn).
description(engwmpan,kfheqdxn).
description(cqwihloe,kfheqdxn).
description(cduxrhkx,kfheqdxn).
description(aewfsyjk,kfheqdxn).
description(jzhvnjbv,kfheqdxn).
description(hhdwvuya,kfheqdxn).
description(vdtjgejf,kfheqdxn).
description(hnrbehjn,kfheqdxn).
description(lzcyiycz,kfheqdxn).
description(jbqdfvrn,nmnooqzu).
description(ribbwtoq,xnqrpuoc).
description(bcaaqxbw,kfheqdxn).
description(zaamhdky,kfheqdxn).
description(lwktbvjq,kfheqdxn).
description(tmcojnai,kfheqdxn).
description(avrsesbh,kfheqdxn).
description(jnuylowp,kfheqdxn).
description(ceunovse,xgxowvyo).
description(ajbksafr,xgxowvyo).
description(zpemfycz,xgxowvyo).
description(tzfqvihp,zfmlhhfz).
description(nboepgqc,rvluolpa).
description(nvdiccpx,djpvorjj).
description(udpirazf,gmmihqox).
description(seolwlcy,hhbqakxj).
description(mcpwbwig,hhbqakxj).
description(rusyftca,fqevunbk).
description(hpqvqpou,iwtonoyh).
description(fshmajsj,iwtonoyh).
description(bgptcqit,iwtonoyh).
description(byqzsjaj,qomunaum).
description(pfwpinrc,bndmcjcq).
description(cjqmyglb,emfggvml).
description(rfustlek,dkweibef).
description(dtgwcjqv,kfheqdxn).
description(ozbubsnf,kfheqdxn).
description(nwqlrizb,wwrumjhp).
description(xbwsusbf,ecuodzjv).
description(dkfeufbh,kqkpnuwf).
description(smvcmohg,dohjdqqy).
description(hpuxyyjh,esslaygp).
description(vluxpnrd,kfheqdxn).
description(irlrtnzb,kfheqdxn).
description(fimkhlxt,kfheqdxn).
description(piakseab,kfheqdxn).
description(xuoqvgim,kfheqdxn).
description(xofyxgmc,kfheqdxn).
description(kqolrgkx,kfheqdxn).
description(fovmpjqt,kfheqdxn).
description(mnwgmogq,kfheqdxn).
description(cflzxmun,kfheqdxn).
description(qdmrhuqc,kfheqdxn).
description(mnlrsdmy,kfheqdxn).
description(zrympsyv,kfheqdxn).
description(sfrwtzvw,kfheqdxn).
description(hnextklx,kfheqdxn).
description(ekmbbmug,kfheqdxn).
description(wyscfyzg,kfheqdxn).
description(ytdoszfx,kfheqdxn).
description(fyokvcda,kfheqdxn).
description(xofyxgmc,kfheqdxn).
description(gdaasvgg,kfheqdxn).
description(ntxheika,kfheqdxn).
description(nyjlyoul,kfheqdxn).
description(mqfexupf,kfheqdxn).
description(ngklfnwi,kfheqdxn).
description(rnewugrg,kfheqdxn).
description(qujymaaz,kfheqdxn).
description(elcajzut,kfheqdxn).
description(cdcwgahh,kfheqdxn).
description(kyguzjwg,kfheqdxn).
description(irlrtnzb,kfheqdxn).
description(kcilomsn,kfheqdxn).
description(fimkhlxt,kfheqdxn).
description(katbjhhv,kfheqdxn).
description(jxjuyyiy,kfheqdxn).
description(ktqfblxt,kfheqdxn).
description(xuoqvgim,kfheqdxn).
description(nsufqczt,kfheqdxn).
description(qpjraqwn,kfheqdxn).
description(gbngnwth,kfheqdxn).
description(piakseab,kfheqdxn).
description(ibcgmdas,mblcspzq).
description(kxbdtpfs,rsgtnzxy).

`;

